### ISSUE TITLE
大佬我问下为什么我一重启cookie就全部被删除了

### ISSUE THREAD

**Issue by alal167** [764763903a/xdd-plus#91]
机器人数据库里有但是脚本库里变量全没了青龙2.9.9

**Comment by shuxin8795** [comment]
我之前2.8版本也是这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "764763903a/xdd-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [764763903a/xdd-plus] 大佬我问下为什么我一重启cookie就全部被删除了 (Issue #91)





  
您是新版本还是什么版本 我更新2.9.9后才出现的还有个2.9.8就没有。。而且我全部重装后依旧如此
  
我是最新版，这个和版本没关系吧，你正常更新后也会出现没ck的现象嘛
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alal167** [comment]
> > 您是新版本还是什么版本 我更新2.9.9后才出现的还有个2.9.8就没有。。而且我全部重装后依旧如此
> 
> 
> 
> 我是最新版，这个和版本没关系吧，你正常更新后也会出现没ck的现象嘛

是的我以为一开始是我自己的问题然后我服务器重置了从头到尾都是新的来一遍等我把cookie录入后一重启面板里就都没了 但是小弟弟数据库里还是有的而且也能正常查询但是脚本库里没有cookie了 也运行不了任务

**Comment by shuxin8795** [comment]
没解决，现在也是。我群里很多人出现同样情况了。ck不同步






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "764763903a/xdd-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 晚上11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [764763903a/xdd-plus] 大佬我问下为什么我一重启cookie就全部被删除了 (Issue #91)





  
我之前2.8版本也是这个问题
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "764763903a/xdd-plus"                                                                                    @.***&gt;;
 
发送时间:&nbsp;2021年10月20日(星期三) 晚上10:54
 
@.***&gt;;
 
@.@.&gt;;
 
主题:&nbsp;Re: [764763903a/xdd-plus] 大佬我问下为什么我一重启cookie就全部被删除了 (Issue #91)
 
您是新版本还是什么版本 我更新2.9.9后才出现的还有个2.9.8就没有。。而且我全部重装后依旧如此
 
我是最新版，这个和版本没关系吧，你正常更新后也会出现没ck的现象嘛
 
—
 
You are receiving this because you commented.
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
Triage notifications on the go with GitHub Mobile for iOS or Android.
  
解决了吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alal167** [comment]
和用什么搭建的没关系。。我把XDD停了就不会把cookie删了。。

**Comment by 764763903a** [comment]
谢谢 楼上已解决
